##
# Author: Nico Alimin (nicoalimin@gmail.com)
# Date: Wednesday, 1st August 2018 11:52:46 pm
# 
# DESCRIPTION
# 
# Copyright (c) 2018 Nico Alimin
##

version: "3"

networks:
  teamgen-net:

volumes:
  teamgen-psql-volume:

services:

  # Cold Storage
  psql:
    restart: always
    # Latest postgres image
    image: postgres
    container_name: psql
    ports:
      # The first part: Where it is externally exposed in the host
      # The second part: Where it is exposed in the container network
      - "5432:5432"
    environment:
      # POSTGRES_DB: ${PG_DATABASE}
      # POSTGRES_USER: ${PG_USER}
      # POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - teamgen-net
    volumes:
      # OLD ONE
      # - teamgen-psql-volume:/var/lib/posgresql/data
      - $HOME/Code/volumes/postgres:/var/lib/postgresql/data
  
  # Database visualization
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - teamgen-net

  server:
    restart: always
    build:
      context: server
    container_name: server
    ports:
      - "3030:3030"
    environment:
      # PG_DATABASE: ${PG_DATABASE}
      # PG_USER: ${PG_USER}
      # PG_PASSWORD: ${PG_PASSWORD}
      TG_PG_DATABASE: api
      TG_PG_USER: postgres
      TG_PG_PASSWORD: password
      TG_PG_HOST: psql
      TG_PG_PORT: 5432
      TG_API_PORT: 3030
    networks:
      - teamgen-net
